name: v3
seed: 1024
fold: 0
kfold: 5
batch_size: 16
model_name: tf_efficientnet_b4_ns
lr: 0.0000185564766155184
image_size: 512
embedding_size: 1024
arcface_scale:  22.963525331959204
arcface_margin: 7.739488019112847
brightness_limit: 0.16
contrast_limit: 0.1
hue_shift_limit: 0.28
sat_shift_limit: 0.225
val_shift_limit: 0.28
scale_limit: 0.0
sub_centers: 4
rotate_limit: 18.394467397006466
warmup_t: 1
epochs: 57
patience: 11
num_model_nos: 366
n_neighbors: 94
random_rotate_p: 0.0
vflip_p: 0.0
hflip_p: 0.0
loss_type: "ArcFaceLoss"
is_fine: true


previous:
  is_fine: false
