name: v3
seed: 1024
fold: 2
kfold: 4
batch_size: 8
model_name: tf_efficientnet_b4_ns
lr: 0.000685564766155184
image_size: 768
embedding_size: 512
arcface_scale: 16.132741524040817
arcface_margin: 24.269744523588212
brightness_limit: 0.00
contrast_limit: 0.000
hue_shift_limit: 0.00
sat_shift_limit: 0.00
val_shift_limit: 0.00
scale_limit: 0.18529016025844874
sub_centers: 2
rotate_limit: 32.394467397006466
warmup_t: 1
epochs: 67
patience: 11
n_neighbors: 200
blur_p: 0.2
vflip_p: 0.0
hflip_p: 0.0
loss_type: "SubCenterArcFaceLoss"

hard_samples:
  - '031/7.jpg'
  - '049/7.jpg'
  - '002/4.jpg'

fine:
  lr: 0.00005
  checkpoint_dir: 'fine-checkpoints'
  scale_limit: 0.0
  rotate_limit: 0.0
  blur_p: 0.0
